---

# This lets us check for EC2 even if we can't gather the facts as expected via Ansible.
# This can happen with new generations of EC2 instances and when IAM permissions are extremely restrictive.
- name: Check if inside AWS EC2.
  uri:
    url: http://169.254.169.254/latest/meta-data
    timeout: 2
  register: ec2_uri_check
  failed_when: False

# Setting these facts makes the conditionals in our main task file more legible and DRY.
- set_fact:
    is_centos7: "{{ (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and ansible_distribution_major_version == '7' }}"
    is_ec2_guest: "{{ ec2_uri_check.status == 200 or ('amazon' in ansible_product_version and ansible_virtualization_role == 'guest') }}"
    is_vmware_guest: "{{ ansible_virtualization_type == 'VMware' and ansible_virtualization_role == 'guest' }}"
