---

- include: fact_check.yml

- include: yum.yml
  when: is_centos7
  become: true
  tags:
  - centos7_yum

- include: setup.yml
  when: is_centos7
  become: true
  tags:
  - centos7_setup

- include: assets.yml
  when: is_centos7
  become: true
  tags:
  - centos7_assets

- include: ec2_assets.yml
  when: is_centos7 and is_ec2_guest
  become: true
  tags:
  - centos7_ec2
  - centos7_assets

- include: ec2_setup.yml
  when: is_centos7 and is_ec2_guest
  become: true
  tags:
  - centos7_ec2

- include: vmware.yml
  when: is_centos7 and is_vmware_guest
  become: true
  tags:
  - centos7_vmware_guest

- include: metal_or_vmware_guest.yml
  when: is_centos7 and (ansible_virtualization_role == "host" or is_vmware_guest)
  become: true
  tags:
  - centos7_metal
  - centos7_vmware_guest
